Created user profile views that enable users to add their profile attributes, such as first name, last name, and mobile, as well as billing and shipping addresses. The shipping address form is only required if it differs from the billing address.
- Implemented views to manage user profile attributes, including handling both billing and shipping addresses.
- Added tests to validate the correctness of the Billing and Shipping forms.
- Currently, only `GET` method tests have been added for the views. Tests for `POST` methods to validate form submissions
 for `UserProfile` are still needed.

- Even though the form tests pass, indicating that the `UserProfile`, `ShippingForm`, and `BillingForm`
  correctly capture the fields, the form fails to pass the billing address details when submitted from the UI. It will only submit
  successfully if the shipping address fields are filled, which should not be required when the billing and shipping addresses are the same.

**Expected Results:**
1. Login.
2. Navigate to the user profile pages.
3. Fill in the required fields: first name, last name, and mobile.
4. Complete the billing address fields; only address line 2 is optional.
5. Leave the shipping address fields blank if it matches the billing address.
6. Leave the rest of the radio buttons in their default state.
7. Submit.
8. The page should redirect to the accounts page.

**Current Results:**
1. Login.
2. Navigate to the user profile pages.
3. Fill in the required fields: first name, last name, and mobile.
4. Complete the billing address fields; only address line 2 is optional.
5. Leave the shipping address fields blank if it matches the billing address.
6. Leave the rest of the radio buttons in their default state.
7. Submit.
8. The page is not redirected to the accounts page. Instead, the following error messages are displayed:

```
"Errors in Billing Address Form:
Error: Address One: - This field is required.
Error: City: - This field is required.
Error: State: - This field is required.
Error: Postcode: - This field is required.
```
This is strange because all billing fields have been filled.

To resolve this issue, I am writing tests for the `POST` views,
 which will help determine whether the problem lies within the views or the frontend.
 The form tests show no errors, indicating that the forms are capturing the data correctly.